# yaml-language-server: $schema=https://raw.githubusercontent.com/cuioss/cuioss-organization/main/.github/actions/read-project-config/schema.json
name: cui-test-value-objects

release:
  current-version: 2.1.1
  next-version: 2.1-SNAPSHOT
  create-github-release: true

sonar:
  project-key: cuioss_cui-test-value-objects

pages:
  reference: cui-test-value-objects
