= cui-test-value-objects

== Status

https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-value-objects[image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-value-objects&metric=alert_status[Quality
Gate Status]]
image:https://github.com/cuioss/cui-test-value-objects/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/cui-test-value-objects/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://maven-badges.herokuapp.com/maven-central/io.github.cuioss/cui-test-value-objects/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/io.github.cuioss/cui-test-value-objects]

https://cuioss.github.io/cui-test-value-objects/index.html[Generated Documentation on github-pages]

== What is it?

A library to support creating unit-tests and much more. Compared to other, more behavior-oriented frameworks like 
link:https://easymock.org/[EasyMock] or link:https://site.mockito.org/[Mockito], it focuses, as its name 
implies, on testing and generating Value-Objects of all sorts. Therefore it is no replacement of said frameworks but 
a supplement. Testing values-objects is about checking properties, constructors, factories, builder,... and the 
dependent canonical object-methods. In addition, the library provides a feature rich generator system. 

== Maven Coordinates

[source,xml]
----
    <dependency>
        <groupId>io.github.cuioss.test</groupId>
        <name>cui-test-value-objects</name>
    </dependency>
----

== Understanding Value-Object testing

There are a number of features that can be used. Therefore, there are different documentation parts for the specific
 features:

* link:src/site/asciidoc/testing-value-objects.adoc[Value-Object-Testing]
* link:src/site/asciidoc/testing-mapper.adoc[Testing Mapper Classes]
* link:src/site/asciidoc/managing-metadata.adoc[Managing Metadata]
* link:src/site/asciidoc/generator-system.adoc[Generator System]
* link:src/site/asciidoc/reflection-system.adoc[Reflection System]
* link:src/site/asciidoc/simple-canonical-object-methods.adoc[Simplified Testing of Canonical Object Methods]


=== Credentials


* `SONAR_TOKEN` -> Sonar-Cloud

They are picked up in the predefined pipeline-configurations:

* `.github/workflows/maven.yml`
* `.github/workflows/maven-release.yml`

Documentation on how to create a signing key can be found https://github.com/cuioss/cui-parent-pom/blob/master/doc/signing_key.adoc[Documentation at cui-parent-pom] 

A sonar token can be derived from https://sonarcloud.io/account/security

=== Further Steps

* `pom.xml`: Adjust `name` and `description` elements
* `src/site/asciidoc/about.adoc`: Adjust content
* Review / Enable the elements under 'Security' Tab
* Add (link) the resulting maven-documentation: https://github.com/cuioss/cuioss.github.io/edit/main/README.md[github.io-documentation] 
