= cui-test-value-objects-junit5

== What is it?

A library to support creating unit-tests and much more. Compared to other, more behavior-oriented frameworks like 
link:https://easymock.org/[EasyMock] or link:https://site.mockito.org/[Mockito], it focuses, as its name 
implies, on testing and generating Value-Objects of all sorts. Therefore it is no replacement of said frameworks but 
a supplement. Testing values-objects is about checking properties, constructors, factories, builder,... and the 
dependent canonical object-methods. In addition, the library provides a feature rich generator system. 

== Maven Coordinates

[listing]
----
<dependency>
    <groupId>de.icw.cui.test</groupId>
    <artifactId>cui-test-value-objects-junit5</artifactId>
    <scope>test</scope>
</dependency>
----

== Understanding Value-Object testing

There are a number of features that can be used. Therefore, there are different documentation parts for the specific
 features:

* link:src/site/asciidoc/testing-value-objects.adoc[Value-Object-Testing]
* link:src/site/asciidoc/testing-mapper.adoc[Testing Mapper Classes]
* link:src/site/asciidoc/managing-metadata.adoc[Managing Metadata]
* link:src/site/asciidoc/generator-system.adoc[Generator System]
* link:src/site/asciidoc/reflection-system.adoc[Reflection System]
* link:src/site/asciidoc/simple-canonical-object-methods.adoc[Simplified Testing of Canonical Object Methods]
